background            #101219

color0                #101219
color1                #8383FF
color2                #64DCF0
color3                #75FCDD
color4                #88AFD3
color5                #98A6EF
color6                #92D1F9
color7                #CCDBD5
color8                #C3B5C0
color9                #BCB9FF
color10               #F7FDFF
color11               #FFFFFF
color12               #C7DFF4
color13               #D3D7FF
color14               #F8FBFF
color15               #D9E6FF

cursor                #CCDBD5

foreground            #CCDBD5

selection_background  #B5C0D4
selection_foreground  #313C4C

# Override obscure colors for starship prompt (these are greys at the end)
color255              #B1C8EC
color254              #3D5472
color253              #BCC7DB
color252              #313C4C
color251              #E3D7FF
color250              #D5C8F9
color249              #FA746F
color248              #871F21

color232              #2B415F
color233              #D5E4FF
color234              #364151
color235              #B5C0D4
color236              #524871
color237              #493F68
color238              #490006
color239              #FF9993
color240              #2B415F
# Somehow 232 doesn't work so i gotta use another number

# Some stuff should specifically use the colors in the middle so they look acceptable in both unthemed light/dark
color243              #B1C8EC
color244              #FA746F
color245              #444850
