-- Generated by matugen — do not edit by hand, changes will be overwritten on
-- the next `switchwall` run (adapted from end-4/dots-hyprland's matugen
-- template, unchanged from upstream). Loaded by hyprland.lua after
-- general.lua/rules.lua so these border/accent colors win over the static
-- ones set there.

hl.config({
    general = {
        col = {
            active_border   = "rgba({{colors.outline_variant.default.hex_stripped}}77)",
            inactive_border = "rgba({{colors.surface_container_low.default.hex_stripped}}33)",
        },
    },
    misc = {
        background_color = "rgba({{colors.surface.dark.hex_stripped}}FF)",
    },
})

hl.window_rule({
    match        = { pin = 1 },
    border_color = "rgba({{colors.primary.default.hex_stripped}}AA) rgba({{colors.primary.default.hex_stripped}}77)",
})
