pragma Singleton
import QtQuick

// Generated by matugen — do not edit by hand, changes will be overwritten
// on the next `switchwall` run. See ~/.config/matugen/config.toml,
// [templates.quickshell_bar_colors]. The hand-written fallback this
// overwrites lives at ~/.config/quickshell/bar/Colors.qml.
QtObject {
    readonly property color background: "#0f1512"
    readonly property color surface: "#1b211e"
    readonly property color primary: "#8bd6b5"
    // Named `text`/`textMuted`, not `onSurface`/`onSurfaceVariant` — QML
    // reserves "on<Capital>" property names for signal handlers.
    readonly property color text: "#dee4df"
    readonly property color textMuted: "#bfc9c2"
    readonly property color outline: "#89938d"
}
