pragma Singleton
import QtQuick

// Generated by matugen — do not edit by hand, changes will be overwritten
// on the next `switchwall` run. See ~/.config/matugen/config.toml,
// [templates.quickshell_bar_colors]. The hand-written fallback this
// overwrites lives at ~/.config/quickshell/bar/Colors.qml.
QtObject {
    readonly property color background: "#111318"
    readonly property color surface: "#1d2024"
    readonly property color primary: "#a3c9fe"
    // Named `text`/`textMuted`, not `onSurface`/`onSurfaceVariant` — QML
    // reserves "on<Capital>" property names for signal handlers.
    readonly property color text: "#e1e2e8"
    readonly property color textMuted: "#c3c6cf"
    readonly property color outline: "#8d9199"
    // Error / destructive roles (M3 error, onError, errorContainer,
    // onErrorContainer). Same on<Capital> rename as text/textMuted above:
    // the two foreground colors become textOnError/textOnErrorContainer.
    readonly property color error: "#ffb4ab"
    readonly property color textOnError: "#690005"
    readonly property color errorContainer: "#93000a"
    readonly property color textOnErrorContainer: "#ffdad6"
}
