pragma Singleton
import QtQuick

// Generated by matugen — do not edit by hand, changes will be overwritten
// on the next `switchwall` run. See ~/.config/matugen/config.toml,
// [templates.quickshell_bar_colors]. The hand-written fallback this
// overwrites lives at ~/.config/quickshell/bar/Colors.qml.
QtObject {
    readonly property color background: "#{{colors.background.default.hex_stripped}}"
    readonly property color surface: "#{{colors.surface_container.default.hex_stripped}}"
    readonly property color primary: "#{{colors.primary.default.hex_stripped}}"
    // Named `text`/`textMuted`, not `onSurface`/`onSurfaceVariant` — QML
    // reserves "on<Capital>" property names for signal handlers.
    readonly property color text: "#{{colors.on_surface.default.hex_stripped}}"
    readonly property color textMuted: "#{{colors.on_surface_variant.default.hex_stripped}}"
    readonly property color outline: "#{{colors.outline.default.hex_stripped}}"
}
