-- Generated by matugen — do not edit by hand, changes will be overwritten on
-- the next `switchwall` run (adapted from end-4/dots-hyprland's matugen
-- template, unchanged from upstream). Loaded by hyprland.lua after
-- general.lua/rules.lua so these border/accent colors win over the static
-- ones set there.

hl.config({
    general = {
        col = {
            active_border   = "rgba(43474e77)",
            inactive_border = "rgba(191c2033)",
        },
    },
    misc = {
        background_color = "rgba(111318FF)",
    },
})

hl.window_rule({
    match        = { pin = 1 },
    border_color = "rgba(a3c9feAA) rgba(a3c9fe77)",
})
