-- Generated by matugen — do not edit by hand, changes will be overwritten
-- on the next `switchwall` run. Adapted from end-4/dots-hyprland's
-- matugen/templates/hyprland/colors.lua: output path only (see config.toml) —
-- this file's content is unchanged from upstream. Loaded by hyprland.lua
-- after general.lua/rules.lua so these border/accent colors win over the
-- static ones set there.

hl.config({
    general = {
        col = {
            active_border   = "rgba(40494477)",
            inactive_border = "rgba(171d1a33)",
        },
    },
    misc = {
        background_color = "rgba(0f1512FF)",
    },
})

hl.window_rule({
    match        = { pin = 1 },
    border_color = "rgba(8bd6b5AA) rgba(8bd6b577)",
})
