

# See https://wiki.hyprland.org/Configuring


#connecting files

$configs = ~/.config/hypr/configs
source=$configs/keybinds.conf
source=$configs/monitor.conf
source=$configs/autostart.conf
source=$configs/settings.conf
source=$configs/animation.conf
source=$configs/decoration.conf

### ENVIRONMENT VARIABLES ###
env = GTK_THEME,Dracula
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24


### WINDOWS AND WORKSPACES ###

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


xwayland {
  force_zero_scaling = true
}
