pragma Singleton
import QtQuick

// Generated by matugen — do not edit by hand, changes will be overwritten
// on the next `switchwall` run. See ~/.config/matugen/config.toml,
// [templates.quickshell_shell_colors]. Output lives at
// ~/.config/quickshell/shell/services/Colors.qml.
QtObject {
    readonly property color background: "#{{colors.background.default.hex_stripped}}"
    readonly property color surface: "#{{colors.surface_container.default.hex_stripped}}"
    readonly property color primary: "#{{colors.primary.default.hex_stripped}}"
    // Named `text`/`textMuted`, not `onSurface`/`onSurfaceVariant` — QML
    // reserves "on<Capital>" property names for signal handlers.
    readonly property color text: "#{{colors.on_surface.default.hex_stripped}}"
    readonly property color textMuted: "#{{colors.on_surface_variant.default.hex_stripped}}"
    readonly property color outline: "#{{colors.outline.default.hex_stripped}}"
    // Error / destructive roles (M3 error, onError, errorContainer,
    // onErrorContainer). Same on<Capital> rename as text/textMuted above:
    // the two foreground colors become textOnError/textOnErrorContainer.
    readonly property color error: "#{{colors.error.default.hex_stripped}}"
    readonly property color textOnError: "#{{colors.on_error.default.hex_stripped}}"
    readonly property color errorContainer: "#{{colors.error_container.default.hex_stripped}}"
    readonly property color textOnErrorContainer: "#{{colors.on_error_container.default.hex_stripped}}"
}
