# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/decoration:blur:size = 13
decoration:blur:xray = 1
decoration:blur:enabled = 1
decoration:blur:size = 5
decoration:blur:passes = 7
animations:enabled = 1
