Net/ThemeName "catppuccin-mocha-blue-standard+default"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "default"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 0
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
