preload = /home/spiderjeff/Downloads/anime-moon-landscape.jpg
wallpaper = DP-3, /home/spiderjeff/Downloads/anime-moon-landscape.jpg


preload = /home/spiderjeff/Downloads/anime-moon.jpg
wallpaper = DP-2, /home/spiderjeff/Downloads/anime-moon.jpg

